### ISSUE TITLE
NotImplementedError: Model int is not supported    OpenNMT-py

### ISSUE THREAD

**Issue by zhangqianjin** [BayesWitnesses/m2cgen#75]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/m2cgen", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/m2cgen/cli.py", line 85, in main
    print(generate_code(args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/m2cgen/cli.py", line 80, in generate_code
    return exporter(model, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/m2cgen/exporters.py", line 47, in export_to_python
    return _export(model, interpreter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/m2cgen/exporters.py", line 70, in _export
    assembler_cls = assemblers.get_assembler_cls(model)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/m2cgen/assemblers/__init__.py", line 76, in get_assembler_cls
    "Model {} is not supported".format(model_name))
NotImplementedError: Model int is not supported

**Comment by izeigerman** [comment]
Hey @zhangqianjin ! You can find the list of supported models in the README. The OpenNMT is not there. Can you please provide more information? Is this a feature request? A bug?

**Comment by izeigerman** [comment]
Closing this issue due to lack of clarity.
